from __future__ import annotations

from punkathon_agent.models.agent import (
    FiltroCancellazione,
    MessageContent,
    MovimentoInput,
    ProfiloUtenteUpdate,
    RisparmioInternoUpdate,
)
from punkathon_agent.models.finance import CATEGORIA_TO_MACRO_CATEGORIA, CategoriaSpesa, MacroCategoriaSpesa

from .attachments import build_user_message_content, resolve_attachment_path, supported_attachment_formats
from .constants import AGENT_NAME, SUPPORTED_ATTACHMENT_MIME_TYPES
from .runtime import (
    build_chat_model,
    create_banking_agent,
    create_punk_agent,
    extract_final_answer,
    get_banking_agent,
    get_punk_agent,
    run_agent_turn,
    run_agent_turn_streaming,
    serialize_conversation,
)
from .tools import (
    aggiungi_movimenti,
    aggiorna_profilo_utente,
    aggiorna_risparmio_interno,
    analizza_budget_attuale,
    analizza_spesa_categorie,
    analizza_spese_complessive,
    analizza_spese_fisse,
    analizza_spese_mese,
    analizza_spese_per_categoria,
    analizza_spese_settimana,
    calcola_budget_residuo_settimana,
    calcola_spese_fisse_mensili,
    cancella_movimenti,
    costruisci_query_sql,
    esegui_query_sql,
    genera_insight_mensili,
    genera_insight_settimanali,
    mostra_schema_database,
    mostra_schema_movimenti,
    ottieni_movimenti_mese_corrente,
    ottieni_profilo_utente,
    riepilogo_movimenti_database,
    stima_spese_fisse_essenziali,
)

__all__ = [
    "AGENT_NAME",
    "SUPPORTED_ATTACHMENT_MIME_TYPES",
    "CategoriaSpesa",
    "MacroCategoriaSpesa",
    "CATEGORIA_TO_MACRO_CATEGORIA",
    "MessageContent",
    "MovimentoInput",
    "FiltroCancellazione",
    "ProfiloUtenteUpdate",
    "RisparmioInternoUpdate",
    "build_chat_model",
    "build_user_message_content",
    "supported_attachment_formats",
    "resolve_attachment_path",
    "aggiungi_movimenti",
    "cancella_movimenti",
    "ottieni_profilo_utente",
    "ottieni_movimenti_mese_corrente",
    "riepilogo_movimenti_database",
    "aggiorna_profilo_utente",
    "aggiorna_risparmio_interno",
    "stima_spese_fisse_essenziali",
    "analizza_spesa_categorie",
    "analizza_budget_attuale",
    "analizza_spese_fisse",
    "analizza_spese_per_categoria",
    "analizza_spese_settimana",
    "calcola_budget_residuo_settimana",
    "analizza_spese_mese",
    "analizza_spese_complessive",
    "calcola_spese_fisse_mensili",
    "genera_insight_settimanali",
    "genera_insight_mensili",
    "costruisci_query_sql",
    "esegui_query_sql",
    "mostra_schema_database",
    "mostra_schema_movimenti",
    "create_punk_agent",
    "get_punk_agent",
    "create_banking_agent",
    "get_banking_agent",
    "extract_final_answer",
    "serialize_conversation",
    "run_agent_turn",
    "run_agent_turn_streaming",
]
