from __future__ import annotations

from .agent import (
    AggregazioneQuerySQL,
    FiltroCancellazione,
    FiltroQuerySQL,
    MessageContent,
    MovimentoInput,
    OrdinamentoQuerySQL,
    PeriodoAnalisi,
    ProfiloUtenteUpdate,
    RichiestaAnalisiCategorieSpesa,
    RichiestaAnalisiMese,
    RichiestaAnalisiPerCategoria,
    RichiestaAnalisiSettimana,
    RichiestaAnalisiStorica,
    RichiestaCostruzioneQuerySQL,
    RichiestaInsightObiettivo,
    RisparmioInternoUpdate,
)
from .api import ApiAttachment, ChatRequest, ChatResponse
from .db import MovimentoBancario, USER_PROFILE_ID, Utente
from .finance import (
    BatchClassificazioneMovimenti,
    CATEGORIA_TO_MACRO_CATEGORIA,
    CategoriaSpesa,
    ClassificazioneMovimento,
    ClassificazioneMovimentoIndicizzata,
    MacroCategoriaSpesa,
    serialize_classification_schema,
)

__all__ = [
    "AggregazioneQuerySQL",
    "ApiAttachment",
    "BatchClassificazioneMovimenti",
    "CATEGORIA_TO_MACRO_CATEGORIA",
    "CategoriaSpesa",
    "ChatRequest",
    "ChatResponse",
    "ClassificazioneMovimento",
    "ClassificazioneMovimentoIndicizzata",
    "FiltroCancellazione",
    "FiltroQuerySQL",
    "MacroCategoriaSpesa",
    "MessageContent",
    "MovimentoBancario",
    "MovimentoInput",
    "OrdinamentoQuerySQL",
    "PeriodoAnalisi",
    "ProfiloUtenteUpdate",
    "RichiestaAnalisiCategorieSpesa",
    "RichiestaAnalisiMese",
    "RichiestaAnalisiPerCategoria",
    "RichiestaAnalisiSettimana",
    "RichiestaAnalisiStorica",
    "RichiestaCostruzioneQuerySQL",
    "RichiestaInsightObiettivo",
    "RisparmioInternoUpdate",
    "USER_PROFILE_ID",
    "Utente",
    "serialize_classification_schema",
]
